# -*- coding: utf-8 -*-
"""mycaptain_ai_project_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124MUo0UZLdpUEvIAsFbDWb14rMaPUn-n
"""

def print_positive_numbers(numbers):
    positive_numbers = [num for num in numbers if num > 0]
    return positive_numbers

list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

positive_list1 = print_positive_numbers(list1)
positive_list2 = print_positive_numbers(list2)
print(f"Input: list1 = {list1} Output: {positive_list1}")
print(f"Input: list2 = {list2} Output: {positive_list2}")
