# -*- coding: utf-8 -*-
"""mycaptain_ai_project_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124MUo0UZLdpUEvIAsFbDWb14rMaPUn-n
"""

E = {0, 2, 4, 6, 8}
N = {1, 2, 3, 4, 5}

union_EN = E | N
intersection_EN = E & N
difference_EN = E - N
symmetric_difference_EN = E ^ N

print(f"Union of E and N is {union_EN}")
print(f"Intersection of E and N is {intersection_EN}")
print(f"Difference of E and N is {difference_EN}")
print(f"Symmetric difference of E and N is {symmetric_difference_EN}")